/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue.ui.presentation;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import javax.swing.JPanel;
import noyauFonctionnel.entity.cartes.Carte;

/**
 *
 * @author Antoine
 */
public class CartePanel extends javax.swing.JPanel {
    
    //Attributs pour l'IHM
    private int posX, posY; // Position 
    private int dimX, dimY; // Dimension
    private int newPosX, newPosY; // Position nouvelles
    private boolean drag = false; // indique si on est entrain de déplacer la carte
    private int posMouseX; // Distance horizontale entre le clic et le coin gauche de la carte
    private int posMouseY; // Distance verticale entre le clic et le coin haut de la carte
    private Carte carte;
    
    /**
     * Creates new form CartePanel
     * @param carte
     */
    public CartePanel(Carte carte, boolean interactif) {
        this.carte = carte;
        initComponents();
        initUI();
        this.setSize(new java.awt.Dimension(100, 130));
        if (!interactif) {
            removeInteractivity();
        }
    }
    
    public void initUI() {
        jLabel1.setText(carte.getNom());
        jLabel2.setText(carte.getDescription());
    }
    
    private void removeInteractivity() {
        for (java.awt.event.MouseMotionListener mml : jPanel1.getMouseMotionListeners()) {
            jPanel1.removeMouseMotionListener(mml);
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
    
        g.setColor(Color.LIGHT_GRAY);
        g.fillRect(0, 0, getWidth(), getHeight());

        g.setColor(Color.RED);
        g.drawRect(0, 0, getWidth() - 1, getHeight() - 1);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setRequestFocusEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(80, 120));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        jLabel1.setText("Nom Carte");
        jPanel1.add(jLabel1);

        jLabel2.setText("- Effet 1 ");
        jPanel1.add(jLabel2);

        jLabel3.setText("- Effet 2");
        jPanel1.add(jLabel3);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        
        drag = true;

        posMouseX = evt.getX();
        posMouseY = evt.getY();

    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        if (drag) {
            int tempPosX = evt.getX() - posMouseX;
            int tempPosY = evt.getY() - posMouseY;
            
            newPosX = getX() + tempPosX;
            newPosY = getY() + tempPosY;
            
            this.setLocation(newPosX, newPosY);
            repaint();                   
        }
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        drag = false;
    }//GEN-LAST:event_jPanel1MouseReleased
    
    public int getPosX() {
        return posX;
    }  
    
    public int getPosY() {
        return posY;
    }

    public int getDimX() {
        return dimX;
    }

    public int getDimY() {
        return dimY;
    }
    
    
    // Vérifie si un clic est à l'intérieur de la carte.
    public boolean clicIn(int pX, int pY) {
        boolean dansLargeur = pX >= posX && pX <= posX + dimX;
        boolean dansHauteur = pY >= posY && pY <= posY + dimY;
        return dansLargeur && dansHauteur;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
