/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue.ui.presentation;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import util.EnumCarte;
import vue.ui.dialog.MainDialog;

/**
 *
 * @author Antoine, Mathéo, Solène
 */
public class CartePanel extends javax.swing.JPanel implements TimeOutListener{
    
    //Attributs pour l'IHM
    private transient MainDialog dialog;
    private JPanel ancienParent;
    private Plateau plateau;
    private JPanel glassPane;
    private final int idCarte;
    private final EnumCarte type;
    private final String nom;
    private final String description;
    /**
     * Creates new form CartePanel
     * @param dialog
     * @param idCarte
     * @param type
     * @param nom
     * @param description
     */
    public CartePanel(MainDialog dialog, int idCarte, EnumCarte type, String nom, String description){
        this.dialog = dialog;
        this.idCarte=idCarte;
        this.type=type;
        this.nom=nom;
        this.description=description;
        initComponents();
        String htmlNom = "<html><body style='width:58px;text-align:center'>" + nom + "</body></html>";
        jLabelNom.setText(htmlNom);
        this.dialog.updateNbCartes();
    }
    
    public void setPointPopularite(int pointPopularite) {
        jLabelEffet1.setText("Popularité : + " + pointPopularite);
        repaint();
    }

    public void setSelfDegat(int selfDegat) {
        jLabelEffet2.setText("Blessure : -" + selfDegat+" vie");
        repaint();
    }

    public void setActionVie(int actionVie) {
        jLabelEffet1.setText("Dégats : " + actionVie+" vie(s)");
        repaint();
    }
    
    public void setGainVie(int gainVie) {
        jLabelEffet1.setText("Santé : +" + gainVie+" vie(s)");
        repaint();
    }
    
    public void setProtection(String protection) {
        jLabelEffet1.setText("<html><body style='width:58px;text-align:center'>Protège de la carte\n" + protection + "</body></html>");
        repaint();
    }
    
    public int getId() {
        return idCarte;
    }
    public EnumCarte getType() {
        return type;
    }
    public String getNom() {
        return nom;
    }
    public String getDescription() {
        return description;
    }

    public void reAddInteractivity() {
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
    }
    
    public void removeInteractivity() {
        for (java.awt.event.MouseMotionListener mml : this.getMouseMotionListeners()) {
            this.removeMouseMotionListener(mml);
        }
        for (java.awt.event.MouseListener ml : this.getMouseListeners()) {
            this.removeMouseListener(ml);
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g.create();
        
        g2d.setColor(Color.WHITE);
        g2d.fillRoundRect(0,0,getWidth(),getHeight(),20,20);
        
        switch (type) {
            case POPULARITE -> g2d.setColor(new Color(74,240,74));//vert
            case ATTAQUE -> g2d.setColor(new Color(240,74,74)); //rouge
            case PROTECTION -> g2d.setColor(new Color(74,74,240)); //bleu
            case ECHANGE -> g2d.setColor(Color.BLACK);
            case GAIN_VIE -> g2d.setColor(Color.PINK);
            default -> System.err.println("Le type n'est pas connu");
        }
        
        g2d.setStroke(new BasicStroke(4,BasicStroke.CAP_ROUND,BasicStroke.JOIN_ROUND));
        g2d.drawRoundRect(0,0,getWidth(),getHeight(),20,20);        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNom = new javax.swing.JLabel();
        jLabelEffet1 = new javax.swing.JLabel();
        jLabelEffet2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(80, 120));
        setPreferredSize(new java.awt.Dimension(100, 120));
        setRequestFocusEnabled(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
        	@Override
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
        	@Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        	@Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jLabelNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNom.setText("Nom Carte");
        jLabelNom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabelNom);

        jLabelEffet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabelEffet1);

        jLabelEffet2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabelEffet2);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (!isEnabled()) return;
        
        // récupération du plateau
        this.plateau = (Plateau) SwingUtilities.getWindowAncestor(this);
        this.glassPane = (JPanel) plateau.getGlassPane();
        this.glassPane.setVisible(true);
        this.glassPane.setLayout(null);

        plateau.setDescription(nom, description);
        
        plateau.getTimerPanel().addTimeModelListener(this); // on ajoute la carte actuelle comme un listener
        
        ancienParent = (JPanel) this.getParent();

        //récupération de la position absolue de la souris
        PointerInfo pointerInfo = MouseInfo.getPointerInfo();
        Point cursorLocation = pointerInfo.getLocation();
        SwingUtilities.convertPointFromScreen(cursorLocation, glassPane);

        //on enlève la carte de la main du joueur
        ancienParent.remove(this);
        ancienParent.revalidate();
        ancienParent.repaint();

        //et on l'ajoute au glassPane
        
        glassPane.add(this);
        this.setLocation(cursorLocation.x - getWidth() / 2, cursorLocation.y - getHeight() / 2);
        glassPane.revalidate();
        glassPane.repaint();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if (!isEnabled()) return;
        
        plateau.getTimerPanel().removeTimeModelListener(this); //on n'écoute plus le décompte si la carte est posée
        
        //récupération de la cible
        JPanel ciblePanel=null;

        if (ancienParent == plateau.getMainJoueurPanel1()) {
            ciblePanel = plateau.getZonePopulariteJoueur1();
        }
        if (ancienParent == plateau.getMainJoueurPanel2()) {
            ciblePanel = plateau.getZonePopulariteJoueur2();
        }
        
        //récupération de la position absolue de la souris
        Point cursorLocation = MouseInfo.getPointerInfo().getLocation();
        SwingUtilities.convertPointFromScreen(cursorLocation, ciblePanel);
        
        //on enlève la carte du glassPane
        glassPane.remove(this);
        glassPane.revalidate();
        glassPane.repaint();
        
        //si la carte est amenée sur la cible on la pose
        if (ciblePanel != null && ciblePanel.contains(cursorLocation)) { 
            dialog.stopTimer();
            ciblePanel.add(this);
            ciblePanel.revalidate();
            ciblePanel.repaint();
            
            // Logique du jeu 
            
            dialog.handleDeposerCarte(idCarte);
            dialog.updateCarteZonePopularite();
            dialog.handleRemoveCarteMainJoueur(idCarte);
            dialog.updateMainJoueur();
            dialog.handleAppliquerEffetCarte(this);
        }
        else { //sinon on la remet dans la main du joueur
            ancienParent.add(this);  // ← remettre dans la main
            ancienParent.revalidate();       // ← recalcul du layout
            ancienParent.repaint();
        }
    }//GEN-LAST:event_formMouseReleased

    public void afterMouseReleased() {        
        dialog.updateJaugeVie();
        dialog.updatePopularite();

        if (dialog.handleVerifierFinDePartie()) {
            dialog.stopTimer();
            dialog.lancerFinJeu();
        } else {
            dialog.handleJoueurPioche();
            dialog.updateMainJoueur();
            dialog.updateNbCartes();

            dialog.handleChangerJoueur();
            dialog.updatePlateau();
            dialog.restartTimer();
        }      
    }
    
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if (!isEnabled()) return;
        
        //récupération de la position absolue de la sourie par rapport à l'écran
        PointerInfo pointerInfo=MouseInfo.getPointerInfo();
        Point cursorLocation=pointerInfo.getLocation();
        SwingUtilities.convertPointFromScreen(cursorLocation,glassPane);
        int x= cursorLocation.x;
        int y= cursorLocation.y;
        
        //déplacer la carte et la centrer sur le curseur
        this.setLocation(x - this.getWidth()/2,y - this.getHeight()/2);
        glassPane.repaint();
    }//GEN-LAST:event_formMouseDragged
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelEffet1;
    private javax.swing.JLabel jLabelEffet2;
    private javax.swing.JLabel jLabelNom;
    // End of variables declaration//GEN-END:variables

    @Override
    public void timeOut(TimeOutEvent event) {
        formMouseReleased(null); //la méthode n'utilisant jamais l'évènement
        this.setEnabled(false); //la carte est posé on la désactive pour ne pas pouvoir la rejouer dans la seconde qui reste
    }
}
