/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue.ui.presentation;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.border.EmptyBorder;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import vue.ui.dialog.MainDialog;

/**
 *
 * @author ember
 */
public class ChoixNom extends javax.swing.JFrame {
    private transient MainDialog dialog;
    private static final String FONTFAMILY = "Verdana";
    
    
    /**
     * Creates new form Plateau
     * 
     * @param dialog
     */
    public ChoixNom(MainDialog dialog) {
        this.dialog = dialog;
        initComponents();
        // bloquer les pseudos à 10 caractères
        this.customJTextFieldPirate1Field.setDocument(new PlainDocument(){
            @Override
            public void insertString(int offs, String str, AttributeSet a) throws BadLocationException{
                if (str != null && (getLength()+str.length())<= 10){
                    super.insertString(offs,str,a);
                }
            }
        });
        this.customJTextFieldPirate2Field.setDocument(new PlainDocument(){
            @Override
            public void insertString(int offs, String str, AttributeSet a) throws BadLocationException{
                if (str != null && (getLength()+str.length())<= 10){
                	super.insertString(offs,str,a);
                }
            }
        });
        
        jLabelBackground.setBounds(0, 0, getWidth(), getHeight());
        setImage();
        setResizable(false);
        
        customJTextFieldPirate2Field.setPlaceholder("Jack Sparrow");
        customJTextFieldPirate1Field.setPlaceholder("Barbe noire");
        customJTextFieldPirate2Field.setBorder(new EmptyBorder(10, 10, 10, 10));
        customJTextFieldPirate1Field.setBorder(new EmptyBorder(10, 10, 10, 10));
        
        BufferedImage icon = ChargeurImage.chargerImage("presentation/icon_ppirate.png");
        Image iconResize = icon.getScaledInstance(64, 64, Image.SCALE_SMOOTH);
        this.setIconImage(iconResize);

        
        BufferedImage image = ChargeurImage.chargerImage("presentation/logo_ppirate.png");

        int taille = 250;

        Image imageEchelle = image.getScaledInstance(taille, taille, Image.SCALE_SMOOTH);
        ImageIcon typeIcon = new ImageIcon(imageEchelle);
        jLabelLogo.setIcon(typeIcon);
        jLabelLogo.setPreferredSize(new Dimension(taille, taille));
        jLabelLogo.setMinimumSize(new Dimension(taille, taille));
        jLabelLogo.setMaximumSize(new Dimension(taille, taille));

        customJButtonStart.setText("LANCER LE JEU");
        customJButtonStart.setBorder(new EmptyBorder(10, 10, 10, 10));

        
        BufferedImage image2 = ChargeurImage.chargerImage("presentation/enter_game.png");
        Image imageEchelle2;
        imageEchelle2 = image2.getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        ImageIcon typeIcon2 = new ImageIcon(imageEchelle2);
        customJButtonStart.setIcon(typeIcon2);
        
        customJTextFieldPirate1Field.addActionListener(e -> customJButtonStart.doClick());
        customJTextFieldPirate2Field.addActionListener(e -> customJButtonStart.doClick());
    }

    public void setImage() {
        BufferedImage image = ChargeurImage.chargerImage("presentation/plateau_background.png");
        Image imageEchelle;
        imageEchelle = image.getScaledInstance(jLabelBackground.getWidth(), jLabelBackground.getHeight(),
                Image.SCALE_SMOOTH);
        ImageIcon typeIcon = new ImageIcon(imageEchelle);
        jLabelBackground.setIcon(typeIcon);
    }
    
    public javax.swing.JLabel getErreurLabel() {
        return this.jLabelErreur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelGaucheLogo = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelDroiteField = new javax.swing.JPanel();
        jPanelZoneNom = new javax.swing.JPanel();
        jPanelZonePirate1 = new javax.swing.JPanel();
        jLabelPirate1Nom = new javax.swing.JLabel();
        customJTextFieldPirate1Field = new vue.ui.presentation.components.CustomJTextField();
        jPanelZonePirate2 = new javax.swing.JPanel();
        jLabelPirate2Nom = new javax.swing.JLabel();
        customJTextFieldPirate2Field = new vue.ui.presentation.components.CustomJTextField();
        jPanelStart = new javax.swing.JPanel();
        jLabelErreur = new javax.swing.JLabel();
        customJButtonStart = new vue.ui.presentation.components.CustomJButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanelBackground = new javax.swing.JPanel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 320));
        setMinimumSize(new java.awt.Dimension(480, 320));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanelMain.setMaximumSize(new java.awt.Dimension(480, 320));
        jPanelMain.setMinimumSize(new java.awt.Dimension(480, 320));
        jPanelMain.setOpaque(false);
        jPanelMain.setPreferredSize(new java.awt.Dimension(480, 320));
        jPanelMain.setLayout(new java.awt.GridLayout(1, 0));

        jPanelGaucheLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelGaucheLogo.setOpaque(false);
        jPanelGaucheLogo.setLayout(new java.awt.BorderLayout());

        jLabelLogo.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabelLogo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabelLogo.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jLabelLogo.setName(""); // NOI18N
        jLabelLogo.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanelGaucheLogo.add(jLabelLogo, java.awt.BorderLayout.CENTER);

        jPanelMain.add(jPanelGaucheLogo);

        jPanelDroiteField.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 10));
        jPanelDroiteField.setOpaque(false);
        jPanelDroiteField.setLayout(new java.awt.GridLayout(2, 0));

        jPanelZoneNom.setOpaque(false);
        jPanelZoneNom.setLayout(new java.awt.GridLayout(2, 0));

        jPanelZonePirate1.setOpaque(false);
        jPanelZonePirate1.setLayout(new java.awt.BorderLayout());

        jLabelPirate1Nom.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelPirate1Nom.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPirate1Nom.setText("Pirate n°1:");
        jPanelZonePirate1.add(jLabelPirate1Nom, java.awt.BorderLayout.CENTER);
        jPanelZonePirate1.add(customJTextFieldPirate1Field, java.awt.BorderLayout.SOUTH);

        jPanelZoneNom.add(jPanelZonePirate1);

        jPanelZonePirate2.setOpaque(false);
        jPanelZonePirate2.setLayout(new java.awt.BorderLayout());

        jLabelPirate2Nom.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelPirate2Nom.setForeground(new java.awt.Color(204, 204, 204));
        jLabelPirate2Nom.setText("Pirate n°2:");
        jPanelZonePirate2.add(jLabelPirate2Nom, java.awt.BorderLayout.CENTER);
        jPanelZonePirate2.add(customJTextFieldPirate2Field, java.awt.BorderLayout.SOUTH);

        jPanelZoneNom.add(jPanelZonePirate2);

        jPanelDroiteField.add(jPanelZoneNom);

        jPanelStart.setOpaque(false);
        jPanelStart.setLayout(new java.awt.GridLayout(3, 0));

        jLabelErreur.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelErreur.setForeground(new java.awt.Color(255, 51, 51));
        jPanelStart.add(jLabelErreur);

        customJButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customJButtonStartActionPerformed(evt);
            }
        });
        jPanelStart.add(customJButtonStart);
        jPanelStart.add(filler2);

        jPanelDroiteField.add(jPanelStart);

        jPanelMain.add(jPanelDroiteField);

        getContentPane().add(jPanelMain);

        jPanelBackground.setMaximumSize(new java.awt.Dimension(480, 320));
        jPanelBackground.setMinimumSize(new java.awt.Dimension(480, 320));
        jPanelBackground.setPreferredSize(new java.awt.Dimension(480, 320));

        jLabelBackground.setMaximumSize(new java.awt.Dimension(480, 320));
        jLabelBackground.setMinimumSize(new java.awt.Dimension(480, 320));
        jLabelBackground.setOpaque(true);
        jLabelBackground.setPreferredSize(new java.awt.Dimension(480, 320));

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBackground);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void customJButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customJButtonStartActionPerformed
        dialog.submitNomsJoueurs(customJTextFieldPirate1Field.getText(), customJTextFieldPirate2Field.getText());
    }//GEN-LAST:event_customJButtonStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vue.ui.presentation.components.CustomJButton customJButtonStart;
    private vue.ui.presentation.components.CustomJTextField customJTextFieldPirate1Field;
    private vue.ui.presentation.components.CustomJTextField customJTextFieldPirate2Field;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelErreur;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPirate1Nom;
    private javax.swing.JLabel jLabelPirate2Nom;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelDroiteField;
    private javax.swing.JPanel jPanelGaucheLogo;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelStart;
    private javax.swing.JPanel jPanelZoneNom;
    private javax.swing.JPanel jPanelZonePirate1;
    private javax.swing.JPanel jPanelZonePirate2;
    // End of variables declaration//GEN-END:variables
}
