/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vue.ui.presentation;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import vue.ui.dialog.MainDialog;



/**
 *
 * @author wer
 */
public class FinPartie extends javax.swing.JDialog {
    private final javax.swing.JFrame parentF;
    private transient MainDialog dialog;
    /**
     * Creates new form FinPartie
     * @param parentF
     * @param modal
     * @param dialog
     */
    public FinPartie(javax.swing.JFrame parentF, boolean modal, MainDialog dialog) {
        super(parentF, modal);
        initComponents();
        this.parentF = parentF;
        this.dialog = dialog;
        setImage();
        setLocationRelativeTo(parentF);
        setResizable(false);
        setJoueurGagnant();
    }
    
    private void setJoueurGagnant() {
        if ((dialog.handleJoueur1Gagne() && dialog.handleJoueur2Gagne()) || (dialog.handleJoueur1Perdu() && dialog.handleJoueur2Perdu())) {
            nomGagnantOuEgalite.setText("ÉGALITÉ"); // ez
            descriptionResultat.setText("Aucun gagnant aujourd'hui !");
        } else if (dialog.handleJoueur1Gagne()) {
            nomGagnantOuEgalite.setText(dialog.getPlateau().getLabelJ1().getText());
            if (dialog.handleJoueur1Perdu()) {
                descriptionResultat.setText("Victoire par sacrifice !");
            } else {
                descriptionResultat.setText("Victoire par popularité !"); // ez
            }
        }  else if (dialog.handleJoueur2Gagne()) {
            nomGagnantOuEgalite.setText(dialog.getPlateau().getLabelJ2().getText());
            if (dialog.handleJoueur2Perdu()) {
                descriptionResultat.setText("Victoire par sacrifice !");
            } else {
                descriptionResultat.setText("Victoire par popularité !"); // ez
            }
        } else if (dialog.handleJoueur2Perdu()) {
            nomGagnantOuEgalite.setText(dialog.getPlateau().getLabelJ1().getText());
            descriptionResultat.setText("Victoire par K.O !"); // ez
        } else if (dialog.handleJoueur1Perdu()) {
            nomGagnantOuEgalite.setText(dialog.getPlateau().getLabelJ2().getText());
            descriptionResultat.setText("Victoire par K.O !"); // ez
        }
    }
    
    private void setImage(){
        BufferedImage image=ChargeurImage.chargerImage("presentation/plateau_background.png");
        Image imageEchelle;
        imageEchelle = image.getScaledInstance(jLabelBackground.getWidth(), jLabelBackground.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon typeIcon=new ImageIcon(imageEchelle);
        jLabelBackground.setIcon(typeIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomGagnantOuEgalite = new javax.swing.JLabel();
        descriptionResultat = new javax.swing.JLabel();
        jPanelBackground = new javax.swing.JPanel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fin du Jeu");
        addWindowListener(new java.awt.event.WindowAdapter() {
        	@Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 750));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 750));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        nomGagnantOuEgalite.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        nomGagnantOuEgalite.setForeground(new java.awt.Color(255, 255, 255));
        nomGagnantOuEgalite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomGagnantOuEgalite.setLabelFor(descriptionResultat);
        nomGagnantOuEgalite.setToolTipText("");
        jPanel1.add(nomGagnantOuEgalite);

        descriptionResultat.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        descriptionResultat.setForeground(new java.awt.Color(255, 255, 255));
        descriptionResultat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(descriptionResultat);

        getContentPane().add(jPanel1);

        jPanelBackground.setMaximumSize(new java.awt.Dimension(1080, 750));
        jPanelBackground.setMinimumSize(new java.awt.Dimension(1080, 750));

        jLabelBackground.setMaximumSize(new java.awt.Dimension(1080, 750));
        jLabelBackground.setMinimumSize(new java.awt.Dimension(1080, 750));
        jLabelBackground.setOpaque(true);
        jLabelBackground.setPreferredSize(new java.awt.Dimension(1080, 750));

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBackground);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        parentF.setVisible(false);
        parentF.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionResultat;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JLabel nomGagnantOuEgalite;
    // End of variables declaration//GEN-END:variables
}
