/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue.ui.presentation;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import util.EnumJoueur;
import vue.ui.dialog.MainDialog;
import vue.ui.presentation.components.JaugeDePopularitePanel;
import vue.ui.presentation.components.JaugeDeViePanel;
import vue.ui.presentation.components.TimerPanel;
import vue.ui.presentation.components.Pioche;

/**
 *
 * @author ember
 */
public class Plateau extends javax.swing.JFrame {
    private transient MainDialog dialog;
    
    /**
     * Creates new form Plateau
     * 
     * @param dialog
     */
    public Plateau(MainDialog dialog) {
        this.dialog = dialog;
        initComponents();
        timerPanel.setDialog(dialog);
        jLabelBackground.setBounds(0, 0, getWidth(), getHeight());
        setImage();
        setResizable(false);
        profilJoueurPanelJoueur1.setJoueur(EnumJoueur.JACK_LE_BORGNE);
        profilNomJoueur2.setJoueur(EnumJoueur.BILL_JAMBE_DE_BOIS);
    }

    public void setImage() {
        BufferedImage image = ChargeurImage.chargerImage("presentation/plateau_background.png");
        Image imageEchelle;
        imageEchelle = image.getScaledInstance(jLabelBackground.getWidth(), jLabelBackground.getHeight(),
                Image.SCALE_SMOOTH);
        ImageIcon typeIcon = new ImageIcon(imageEchelle);
        jLabelBackground.setIcon(typeIcon);
        
        BufferedImage icon = ChargeurImage.chargerImage("presentation/icon_ppirate.png");
        Image iconResize = icon.getScaledInstance(64, 64, Image.SCALE_SMOOTH);
        this.setIconImage(iconResize);
    }
    
    public javax.swing.JLabel getLabelJ1() {
        return jLabelNomJoueur1;
    }
    
    public javax.swing.JLabel getLabelJ2() {
        return jLabelNomJoueur2;
    }
    
    public JaugeDeViePanel getJaugeVieJ1() {
        return jaugeDeViePanelJoueur1;
    }
    
    public JaugeDeViePanel getJaugeVieJ2() {
        return jaugeDeViePanelJoueur2;
    }
    
    public JaugeDePopularitePanel getJaugePopJ1() {
        return jaugeDePopularitePanelJoueur1;
    }
    
    public JaugeDePopularitePanel getJaugePopJ2() {
        return jaugeDePopularitePanelJoueur2;
    }
     
    public TimerPanel getTimerPanel() {
        return timerPanel;
    }
    
    public Pioche getPioche(){
        return pioche;
    }
    
    public JPanel getMainJoueurPanel1() {
        return mainJoueurPanelJoueur1;
    }

    public JPanel getMainJoueurPanel2() {
        return mainJoueurPanelJoueur2;
    }

    public JPanel getZonePopulariteJoueur2() {
        return zonePopularitePanelJoueur2;
    }

    public JPanel getZonePopulariteJoueur1() {
        return zonePopularitePanelJoueur1;
    }
    
    public JPanel getZoneAction() {
        return jPanelZoneAction1;
    }
    
    public void setDescription(String titre, String description){
        descriptionPanel.setTitre(titre);
        String htmlDescription = "<html><body style='width:100px;text-align:center'>"+description + "</body></html>";
        descriptionPanel.setDescription(htmlDescription);
        repaint();
    }
    
    public void setTour(String nomJoueur){
        timerPanel.setTour(nomJoueur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelZoneJeu = new javax.swing.JPanel();
        jPanelCommun = new javax.swing.JPanel();
        jPanelZonesPopularite = new javax.swing.JPanel();
        zonePopularitePanelJoueur2 = new vue.ui.presentation.components.ZonePopularitePanel();
        zonePopularitePanelJoueur1 = new vue.ui.presentation.components.ZonePopularitePanel();
        jPanelZoneAction = new javax.swing.JPanel();
        fillerZoneAction1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 150), new java.awt.Dimension(32767, 50));
        jPanelZoneAction1 = new vue.ui.presentation.components.ZonePopularitePanel();
        fillerZoneAction2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        jPanelPioche = new javax.swing.JPanel();
        fillerPioche1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 150), new java.awt.Dimension(32767, 50));
        pioche = new vue.ui.presentation.components.Pioche();
        fillerPioche2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        jPanelJoueur1 = new javax.swing.JPanel();
        jPanelInfosJoueur1 = new javax.swing.JPanel();
        jaugeDePopularitePanelJoueur1 = new vue.ui.presentation.components.JaugeDePopularitePanel();
        jaugeDeViePanelJoueur1 = new vue.ui.presentation.components.JaugeDeViePanel();
        profilJoueurPanelJoueur1 = new vue.ui.presentation.components.ProfilJoueurPanel();
        jPanelNomJoueur1 = new javax.swing.JPanel();
        jLabelNomJoueur1 = new javax.swing.JLabel();
        jPanelMainJoueur1 = new javax.swing.JPanel();
        filler1MainJ1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        mainJoueurPanelJoueur1 = new vue.ui.presentation.components.MainJoueurPanel();
        filler2MainJ1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 2), new java.awt.Dimension(500, 32767));
        timerPanel = new vue.ui.presentation.components.TimerPanel();
        jPanelJoueur2 = new javax.swing.JPanel();
        jPanelInfosJoueur2 = new javax.swing.JPanel();
        jaugeDePopularitePanelJoueur2 = new vue.ui.presentation.components.JaugeDePopularitePanel();
        jaugeDeViePanelJoueur2 = new vue.ui.presentation.components.JaugeDeViePanel();
        profilNomJoueur2 = new vue.ui.presentation.components.ProfilJoueurPanel();
        jPanelNomJoueur2 = new javax.swing.JPanel();
        jLabelNomJoueur2 = new javax.swing.JLabel();
        jPanelMainJoueur2 = new javax.swing.JPanel();
        filler1MainJ2 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        mainJoueurPanelJoueur2 = new vue.ui.presentation.components.MainJoueurPanel();
        filler2MainJ2 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        descriptionPanel = new vue.ui.presentation.components.DescriptionPanel();
        jPanelBackground = new javax.swing.JPanel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 750));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanelZoneJeu.setMaximumSize(new java.awt.Dimension(1080, 750));
        jPanelZoneJeu.setMinimumSize(new java.awt.Dimension(1080, 750));
        jPanelZoneJeu.setOpaque(false);
        jPanelZoneJeu.setPreferredSize(new java.awt.Dimension(1080, 750));
        jPanelZoneJeu.setLayout(new java.awt.BorderLayout());

        jPanelCommun.setOpaque(false);
        jPanelCommun.setLayout(new java.awt.BorderLayout());

        jPanelZonesPopularite.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        jPanelZonesPopularite.setOpaque(false);
        jPanelZonesPopularite.setLayout(new java.awt.GridLayout(2, 0, 0, 4));
        jPanelZonesPopularite.add(zonePopularitePanelJoueur2);
        jPanelZonesPopularite.add(zonePopularitePanelJoueur1);

        jPanelCommun.add(jPanelZonesPopularite, java.awt.BorderLayout.CENTER);

        jPanelZoneAction.setOpaque(false);
        jPanelZoneAction.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanelZoneAction.setLayout(new java.awt.GridLayout(3, 0));
        jPanelZoneAction.add(fillerZoneAction1);

        jPanelZoneAction1.setMinimumSize(new java.awt.Dimension(10, 155));
        jPanelZoneAction1.setPreferredSize(new java.awt.Dimension(100, 155));
        jPanelZoneAction.add(jPanelZoneAction1);
        jPanelZoneAction.add(fillerZoneAction2);

        jPanelCommun.add(jPanelZoneAction, java.awt.BorderLayout.WEST);

        jPanelPioche.setOpaque(false);
        jPanelPioche.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanelPioche.setLayout(new java.awt.GridLayout(3, 0));
        jPanelPioche.add(fillerPioche1);
        jPanelPioche.add(pioche);
        jPanelPioche.add(fillerPioche2);

        jPanelCommun.add(jPanelPioche, java.awt.BorderLayout.EAST);

        jPanelZoneJeu.add(jPanelCommun, java.awt.BorderLayout.CENTER);

        jPanelJoueur1.setOpaque(false);
        jPanelJoueur1.setLayout(new java.awt.BorderLayout());

        jPanelInfosJoueur1.setOpaque(false);
        jPanelInfosJoueur1.setLayout(new java.awt.BorderLayout());

        jaugeDePopularitePanelJoueur1.setBackground(null);
        jaugeDePopularitePanelJoueur1.setOpaque(false);

        javax.swing.GroupLayout jaugeDePopularitePanelJoueur1Layout = new javax.swing.GroupLayout(jaugeDePopularitePanelJoueur1);
        jaugeDePopularitePanelJoueur1.setLayout(jaugeDePopularitePanelJoueur1Layout);
        jaugeDePopularitePanelJoueur1Layout.setHorizontalGroup(
            jaugeDePopularitePanelJoueur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        jaugeDePopularitePanelJoueur1Layout.setVerticalGroup(
            jaugeDePopularitePanelJoueur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanelInfosJoueur1.add(jaugeDePopularitePanelJoueur1, java.awt.BorderLayout.EAST);

        jaugeDeViePanelJoueur1.setOpaque(false);
        jPanelInfosJoueur1.add(jaugeDeViePanelJoueur1, java.awt.BorderLayout.NORTH);

        profilJoueurPanelJoueur1.setOpaque(false);
        jPanelInfosJoueur1.add(profilJoueurPanelJoueur1, java.awt.BorderLayout.CENTER);

        jPanelNomJoueur1.setOpaque(false);
        jPanelNomJoueur1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelNomJoueur1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNomJoueur1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomJoueur1.setText("JACK SPARROW");
        jPanelNomJoueur1.add(jLabelNomJoueur1);

        jPanelInfosJoueur1.add(jPanelNomJoueur1, java.awt.BorderLayout.SOUTH);

        jPanelJoueur1.add(jPanelInfosJoueur1, java.awt.BorderLayout.WEST);

        jPanelMainJoueur1.setOpaque(false);
        jPanelMainJoueur1.setLayout(new javax.swing.BoxLayout(jPanelMainJoueur1, javax.swing.BoxLayout.LINE_AXIS));
        jPanelMainJoueur1.add(filler1MainJ1);
        jPanelMainJoueur1.add(mainJoueurPanelJoueur1);
        jPanelMainJoueur1.add(filler2MainJ1);

        timerPanel.setMinimumSize(new java.awt.Dimension(100, 200));
        timerPanel.setPreferredSize(new java.awt.Dimension(219, 113));
        jPanelMainJoueur1.add(timerPanel);

        jPanelJoueur1.add(jPanelMainJoueur1, java.awt.BorderLayout.CENTER);

        jPanelZoneJeu.add(jPanelJoueur1, java.awt.BorderLayout.SOUTH);

        jPanelJoueur2.setOpaque(false);
        jPanelJoueur2.setLayout(new java.awt.BorderLayout());

        jPanelInfosJoueur2.setOpaque(false);
        jPanelInfosJoueur2.setLayout(new java.awt.BorderLayout());

        jaugeDePopularitePanelJoueur2.setOpaque(false);

        javax.swing.GroupLayout jaugeDePopularitePanelJoueur2Layout = new javax.swing.GroupLayout(jaugeDePopularitePanelJoueur2);
        jaugeDePopularitePanelJoueur2.setLayout(jaugeDePopularitePanelJoueur2Layout);
        jaugeDePopularitePanelJoueur2Layout.setHorizontalGroup(
            jaugeDePopularitePanelJoueur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jaugeDePopularitePanelJoueur2Layout.setVerticalGroup(
            jaugeDePopularitePanelJoueur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        jPanelInfosJoueur2.add(jaugeDePopularitePanelJoueur2, java.awt.BorderLayout.EAST);

        jaugeDeViePanelJoueur2.setOpaque(false);
        jPanelInfosJoueur2.add(jaugeDeViePanelJoueur2, java.awt.BorderLayout.SOUTH);

        profilNomJoueur2.setOpaque(false);
        jPanelInfosJoueur2.add(profilNomJoueur2, java.awt.BorderLayout.CENTER);

        jPanelNomJoueur2.setOpaque(false);
        jPanelNomJoueur2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelNomJoueur2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabelNomJoueur2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomJoueur2.setText("JACK SPARROW");
        jPanelNomJoueur2.add(jLabelNomJoueur2);

        jPanelInfosJoueur2.add(jPanelNomJoueur2, java.awt.BorderLayout.NORTH);

        jPanelJoueur2.add(jPanelInfosJoueur2, java.awt.BorderLayout.WEST);

        jPanelMainJoueur2.setOpaque(false);
        jPanelMainJoueur2.setLayout(new javax.swing.BoxLayout(jPanelMainJoueur2, javax.swing.BoxLayout.LINE_AXIS));
        jPanelMainJoueur2.add(filler1MainJ2);
        jPanelMainJoueur2.add(mainJoueurPanelJoueur2);
        jPanelMainJoueur2.add(filler2MainJ2);
        jPanelMainJoueur2.add(descriptionPanel);

        jPanelJoueur2.add(jPanelMainJoueur2, java.awt.BorderLayout.CENTER);

        jPanelZoneJeu.add(jPanelJoueur2, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanelZoneJeu);

        jPanelBackground.setMaximumSize(new java.awt.Dimension(1080, 750));
        jPanelBackground.setMinimumSize(new java.awt.Dimension(1080, 750));
        jPanelBackground.setPreferredSize(new java.awt.Dimension(1080, 750));

        jLabelBackground.setMaximumSize(new java.awt.Dimension(1080, 750));
        jLabelBackground.setMinimumSize(new java.awt.Dimension(1080, 750));
        jLabelBackground.setOpaque(true);
        jLabelBackground.setPreferredSize(new java.awt.Dimension(1080, 750));

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBackground);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vue.ui.presentation.components.DescriptionPanel descriptionPanel;
    private javax.swing.Box.Filler filler1MainJ1;
    private javax.swing.Box.Filler filler1MainJ2;
    private javax.swing.Box.Filler filler2MainJ1;
    private javax.swing.Box.Filler filler2MainJ2;
    private javax.swing.Box.Filler fillerPioche1;
    private javax.swing.Box.Filler fillerPioche2;
    private javax.swing.Box.Filler fillerZoneAction1;
    private javax.swing.Box.Filler fillerZoneAction2;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelNomJoueur1;
    private javax.swing.JLabel jLabelNomJoueur2;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelCommun;
    private javax.swing.JPanel jPanelInfosJoueur1;
    private javax.swing.JPanel jPanelInfosJoueur2;
    private javax.swing.JPanel jPanelJoueur1;
    private javax.swing.JPanel jPanelJoueur2;
    private javax.swing.JPanel jPanelMainJoueur1;
    private javax.swing.JPanel jPanelMainJoueur2;
    private javax.swing.JPanel jPanelNomJoueur1;
    private javax.swing.JPanel jPanelNomJoueur2;
    private javax.swing.JPanel jPanelPioche;
    private javax.swing.JPanel jPanelZoneAction;
    private vue.ui.presentation.components.ZonePopularitePanel jPanelZoneAction1;
    private javax.swing.JPanel jPanelZoneJeu;
    private javax.swing.JPanel jPanelZonesPopularite;
    private vue.ui.presentation.components.JaugeDePopularitePanel jaugeDePopularitePanelJoueur1;
    private vue.ui.presentation.components.JaugeDePopularitePanel jaugeDePopularitePanelJoueur2;
    private vue.ui.presentation.components.JaugeDeViePanel jaugeDeViePanelJoueur1;
    private vue.ui.presentation.components.JaugeDeViePanel jaugeDeViePanelJoueur2;
    private vue.ui.presentation.components.MainJoueurPanel mainJoueurPanelJoueur1;
    private vue.ui.presentation.components.MainJoueurPanel mainJoueurPanelJoueur2;
    private vue.ui.presentation.components.Pioche pioche;
    private vue.ui.presentation.components.ProfilJoueurPanel profilJoueurPanelJoueur1;
    private vue.ui.presentation.components.ProfilJoueurPanel profilNomJoueur2;
    private vue.ui.presentation.components.TimerPanel timerPanel;
    private vue.ui.presentation.components.ZonePopularitePanel zonePopularitePanelJoueur1;
    private vue.ui.presentation.components.ZonePopularitePanel zonePopularitePanelJoueur2;
    // End of variables declaration//GEN-END:variables
}
