/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue.ui.presentation.components;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Solène
 */
public class DescriptionPanel extends javax.swing.JPanel {
    private final float opacite;
    private static final int BORDURE = 15;
    /**
     * Creates new form DescriptionPanel
     */
    
    public DescriptionPanel() {
        this.opacite = 0.5f;
        initComponents();
        jScrollPaneDescription.getViewport().setOpaque(false);
    }
    
    @Override
    protected void paintComponent(Graphics g){
        Graphics2D g2d = (Graphics2D) g.create();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER,this.opacite)); // baisse l'opacité du panel
        g2d.setColor(Color.BLACK);
        g2d.fill(new RoundRectangle2D.Float(0,0,getWidth(),getHeight(),BORDURE,BORDURE));
        g2d.dispose();
        
        super.paintComponent(g);
    }
    
    public void setDescription(String description){
        jLabelDescription.setText(description);
    }
    
    public void setTitre(String titre){
        jLabelTitre.setText(titre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitre = new javax.swing.JLabel();
        jScrollPaneDescription = new javax.swing.JScrollPane();
        jLabelDescription = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(100, 200));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(219, 113));

        jLabelTitre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Description");

        jScrollPaneDescription.setBorder(null);
        jScrollPaneDescription.setOpaque(false);

        jLabelDescription.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPaneDescription.setViewportView(jLabelDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPaneDescription, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDescription))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JScrollPane jScrollPaneDescription;
    // End of variables declaration//GEN-END:variables
}
