/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Gvue.uiForms/JPanel.java to edit this template
 */
package vue.ui.presentation.components;

/**
 *
 * @author Solène
 */
public class JaugeDeViePanel extends javax.swing.JPanel {

    /**
     * Creates new form JaugeDeVie
     */
    public JaugeDeViePanel() {
        initComponents();
        viePanel1.setPleine(true);
        viePanel2.setPleine(true);
        viePanel3.setPleine(true);
        viePanel4.setPleine(true);
        viePanel5.setPleine(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viePanel1 = new vue.ui.presentation.components.ViePanel();
        viePanel2 = new vue.ui.presentation.components.ViePanel();
        viePanel3 = new vue.ui.presentation.components.ViePanel();
        viePanel4 = new vue.ui.presentation.components.ViePanel();
        viePanel5 = new vue.ui.presentation.components.ViePanel();

        setMaximumSize(new java.awt.Dimension(150, 30));
        setMinimumSize(new java.awt.Dimension(150, 30));
        setPreferredSize(new java.awt.Dimension(150, 30));
        setLayout(new java.awt.GridLayout(1, 5));

        javax.swing.GroupLayout viePanel1Layout = new javax.swing.GroupLayout(viePanel1);
        viePanel1.setLayout(viePanel1Layout);
        viePanel1Layout.setHorizontalGroup(
            viePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        viePanel1Layout.setVerticalGroup(
            viePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(viePanel1);

        javax.swing.GroupLayout viePanel2Layout = new javax.swing.GroupLayout(viePanel2);
        viePanel2.setLayout(viePanel2Layout);
        viePanel2Layout.setHorizontalGroup(
            viePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        viePanel2Layout.setVerticalGroup(
            viePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(viePanel2);

        javax.swing.GroupLayout viePanel3Layout = new javax.swing.GroupLayout(viePanel3);
        viePanel3.setLayout(viePanel3Layout);
        viePanel3Layout.setHorizontalGroup(
            viePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        viePanel3Layout.setVerticalGroup(
            viePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(viePanel3);

        javax.swing.GroupLayout viePanel4Layout = new javax.swing.GroupLayout(viePanel4);
        viePanel4.setLayout(viePanel4Layout);
        viePanel4Layout.setHorizontalGroup(
            viePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        viePanel4Layout.setVerticalGroup(
            viePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(viePanel4);

        javax.swing.GroupLayout viePanel5Layout = new javax.swing.GroupLayout(viePanel5);
        viePanel5.setLayout(viePanel5Layout);
        viePanel5Layout.setHorizontalGroup(
            viePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        viePanel5Layout.setVerticalGroup(
            viePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(viePanel5);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vue.ui.presentation.components.ViePanel viePanel1;
    private vue.ui.presentation.components.ViePanel viePanel2;
    private vue.ui.presentation.components.ViePanel viePanel3;
    private vue.ui.presentation.components.ViePanel viePanel4;
    private vue.ui.presentation.components.ViePanel viePanel5;
    // End of variables declaration//GEN-END:variables
}
