/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue.ui.presentation.components;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author Hadrien Lagier, David Marquet
 */
public class Pioche extends javax.swing.JPanel {

    /**
     * Creates new form PanelPioche
     */
    public Pioche() {
        initComponents();
        setLayout(null);
        jLabelNbCarte.setBounds(20, 5, getWidth(), 30);
        jLabelNbCarte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                jLabelNbCarte.setBounds(0, 35, getWidth(), 30);
            }
        });
        }
    
    public void setNbCartes(int nb){
        jLabelNbCarte.setText(String.valueOf(nb));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNbCarte = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(300, 300));

        jLabelNbCarte.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelNbCarte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNbCarte, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabelNbCarte)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D)g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        int x = 0;
        int y = 0;
        int width = 100;
        int height = 110;
        int arc = 30;
            // afficher le dos d'une carte
            GradientPaint gradient = new GradientPaint(x, y, new Color(150, 0, 0), x + width*1.0f, y + height*1.0f, new Color(255, 50, 50));
            g2d.setPaint(gradient);
            g2d.fillRoundRect(x, y, width, height, arc, arc);

            g2d.setColor(Color.WHITE);
            g2d.setStroke(new BasicStroke(4));
            g2d.drawRoundRect(x, y, width, height, arc, arc);
            
            super.paintComponent(g);
        }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNbCarte;
    // End of variables declaration//GEN-END:variables
}
