/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue.ui.presentation.components;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import vue.ui.dialog.MainDialog;

/**
 *
 * @author David Marquet
 */
public class TimerPanel extends javax.swing.JPanel {
    private MainDialog dialog;

    /**
     * Creates new form TimerPanel
     */
    javax.swing.Timer timer;
    private int decompte;
    private static final int TEMPS = 10;
    private float opacite;
    private static final int BORDURE = 15;
    
    public TimerPanel(MainDialog dialog) {
        this.dialog = dialog;
        this.opacite = 0.5f;
        initComponents();
        this.timer = new javax.swing.Timer(1000, (e) -> { timerEventHandler(e); });
        this.decompte = TEMPS;
    }
    
    public void stop() {
        timer.stop();
    }
    
    public void start() {
        timer.start();
    }
    
    @Override
    protected void paintComponent(Graphics g){
        Graphics2D g2d = (Graphics2D) g.create();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER,this.opacite)); // baisse l'opacité du panel
        g2d.setColor(Color.BLACK);
        g2d.fill(new RoundRectangle2D.Float(0,0,getWidth(),getHeight(),BORDURE,BORDURE));
        
        g2d.dispose();
        
        super.paintComponent(g);
    }
    
    private void timerEventHandler(java.awt.event.ActionEvent e) {
        this.decompte --;
        if (this.decompte < 0){
            timerTxt.setText("<html><body style='text-align:center'>"+String.valueOf("Temps écoulé")+"</body></html>");
            timer.stop();
            dialog.handleChangerJoueur();
            System.out.println("On change de joueur car le temps est écoulé.");
            dialog.updatePlateau();
            restartTimer();
        }
        else{
           timerTxt.setText("<html><body style='text-align:center'>"+String.valueOf(this.decompte)+"</body></html>");
        }
        repaint();
    }
    
    public void restartTimer() {
        if (timer.isRunning()){
            timer.stop();
        }
        this.decompte = TEMPS;
        timer.start();
        repaint();
    }
    
    public void updateTimer(int timeLeft) {
        this.decompte = timeLeft;
        repaint();
    }
    
    public int getDecompte() {
        return decompte;
    }
    
    public javax.swing.Timer getTimer() {
        return timer;
    }
    
    public void setTour(String nomJoueur){
        tourLabel.setText("<html><body style='width:185px;text-align:center'>" +"Tour de "+ nomJoueur + "</body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomTimer = new javax.swing.JLabel();
        timerTxt = new javax.swing.JLabel();
        tourLabel = new javax.swing.JLabel();

        setOpaque(false);

        nomTimer.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        nomTimer.setForeground(new java.awt.Color(255, 255, 255));
        nomTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomTimer.setText("<html><body style='text-align:center'>TEMPS RESTANT</body></html>");

        timerTxt.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        timerTxt.setForeground(new java.awt.Color(255, 255, 255));
        timerTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerTxt.setText(String.valueOf(TEMPS));

        tourLabel.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        tourLabel.setForeground(new java.awt.Color(255, 255, 255));
        tourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tourLabel.setText("Tour de");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(timerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nomTimer, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(nomTimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tourLabel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomTimer;
    private javax.swing.JLabel timerTxt;
    private javax.swing.JLabel tourLabel;
    // End of variables declaration//GEN-END:variables
}
