/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vue.ui.presentation.components;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Path2D;

/**
 *
 * @author Solène
 */
public class ViePanel extends javax.swing.JPanel {

    boolean pleine;
    
    /**
     * Creates new form Vie
     */
    public ViePanel() {
        initComponents();
    }

    public boolean isPleine() {
        return pleine;
    }

    public void setPleine(boolean pleine) {
        this.pleine = pleine;
        repaint();
    }
    
    private Path2D creerCheminCoeur(float x, float y, float largeur, float hauteur) {
        float eiX = x + largeur / 2;  // point d'extrémité inférieur X
        float eiY = y + hauteur;     // point d'extrémité inférieur Y

        float c1DX = largeur  * 0.968f;  // delta X du point de contrôle 1
        float c1DY = hauteur * 0.672f;  // delta Y du point de contrôle 1
        float c2DX = largeur  * 0.281f;  // delta X du point de contrôle 2
        float c2DY = hauteur * 1.295f;  // delta Y du point de contrôle 2
        float esDY = hauteur * 0.850f;  // delta Y du point d'extrémité supérieur

        Path2D.Float cheminCoeur = new Path2D.Float();
        cheminCoeur.moveTo(eiX, eiY);       // point d'extrémité inférieur
        // côté gauche du coeur
        cheminCoeur.curveTo(eiX - c1DX, eiY - c1DY,   // point de contrôle 1
                eiX - c2DX, eiY - c2DY,   // point de contrôle 2
                eiX       , eiY - esDY);  // point d'extrémité supérieur
        // côté droit du coeur
        cheminCoeur.curveTo(eiX + c2DX, eiY - c2DY,   // point de contrôle 2
                eiX + c1DX, eiY - c1DY,   // point de contrôle 1
                eiX       , eiY);         // point d'extrémité inférieur
        return cheminCoeur;
    }

    
    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        

        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        
        int margin = 2;   // marge autour du coeur
        int panelLargeur=this.getWidth();
        int panelHauteur=this.getHeight();
        int tailleBoite = Math.min(panelLargeur, panelHauteur) - margin * 2;
        float boiteX = (panelLargeur - tailleBoite) / 2.0f;
        float boiteY = (panelHauteur - tailleBoite) / 2.0f;
        
        Path2D coeur=creerCheminCoeur(boiteX,boiteY,tailleBoite,tailleBoite);
        
        g2d.setStroke(new BasicStroke(2));
        g2d.draw(coeur);
        
        if (pleine){ // si le coeur est plein on le colore en rouge
            g2d.setColor(Color.red);
            g2d.fill(coeur);
        }else{ //sinon en noir
            g2d.setColor(Color.black);
            g2d.fill(coeur);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(30, 30));
        setMinimumSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
