/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary.presentation;

import boundary.AdaptateurDuNoyauFonctionnel;
import boundary.presentation.components.ViePanel;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import util.EnumJoueur;
// import dialog.

/**
 *
 * @author ember
 */
public class Plateau extends javax.swing.JFrame {
    private AdaptateurDuNoyauFonctionnel noyau;

    /**
     * Creates new form Plateau
     * @param noyau
     */
    public Plateau(AdaptateurDuNoyauFonctionnel noyau) {
        this.noyau = noyau;
        initComponents();
        backgroundLabel.setBounds(0, 0, getWidth(), getHeight());
        setImage();
        setResizable(false);
        profilJoueurPanel1.setJoueur(EnumJoueur.JACK_LE_BORGNE);
        profilJoueurPanel2.setJoueur(EnumJoueur.BILL_JAMBE_DE_BOIS);
        
        updatePlateau();
        
        // Set Adaptateur Noyau Fonctionnel 
        pioche1.setAdaptateur(noyau);
    }

    public void setImage(){
        BufferedImage image=ChargeurImage.chargerImage("presentation/plateau_background.png");
        Image imageEchelle;
        imageEchelle = image.getScaledInstance(backgroundLabel.getWidth(), backgroundLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon typeIcon=new ImageIcon(imageEchelle);
        backgroundLabel.setIcon(typeIcon);
    }
    
    public AdaptateurDuNoyauFonctionnel getAdaptateurNoyau() {
        return noyau;
    }
    
    public final void updatePlateau() {
        afficherCarteZonePopularite();
        updateJaugeVie();
    }
    
    public void afficherCarteZonePopularite() {
        System.out.println("IN");
        zonePopularitePanel1.removeAll();
        zonePopularitePanel2.removeAll();
        
        noyau.getControlJeu().getZonePopulariteJ1().forEach(carte -> {
            System.out.println("Carte ajoutée dans zone Popularité du joueur 1 : " + carte);
            CartePanel c = new CartePanel(carte, false);
            zonePopularitePanel1.add(c);
        });
        
        noyau.getControlJeu().getZonePopulariteJ2().forEach(carte -> {
            System.out.println("Carte ajoutée dans zone Popularité du joueur 2 : " + carte);
            CartePanel c = new CartePanel(carte, false);
            zonePopularitePanel2.add(c);
        });
        
        zonePopularitePanel1.revalidate();
        zonePopularitePanel1.repaint();
        zonePopularitePanel2.revalidate();
        zonePopularitePanel2.repaint();
    }
    
    public void updateJaugeVie() {
        int vie_j1 = noyau.getControlJoueur().getPointDeVieJ1();
        int vie_j2 = noyau.getControlJoueur().getPointDeVieJ2();
        System.out.println("vie joueur1 = " + vie_j1 + " vie joueur2 = " + vie_j2);
        
        for (int i = 0; i < 5; i++){
            if (i <= vie_j1) {
                System.out.println("j1");
                ViePanel vies = (ViePanel) jaugeDeViePanel1.getComponent(i);
                vies.setPleine(true);
            }
            if (i <= vie_j2) {
                System.out.println("j2");
                ViePanel vies = (ViePanel) jaugeDeViePanel2.getComponent(i);
                vies.setPleine(true);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCommun = new javax.swing.JPanel();
        panelZonesPopularite = new javax.swing.JPanel();
        zonePopularitePanel1 = new boundary.presentation.components.ZonePopularitePanel();
        zonePopularitePanel2 = new boundary.presentation.components.ZonePopularitePanel();
        panelZoneAction = new javax.swing.JPanel();
        fillerZoneAction1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 150), new java.awt.Dimension(32767, 50));
        panelZoneAction1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        fillerZoneAction2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        panelPioche = new javax.swing.JPanel();
        fillerPioche1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 150), new java.awt.Dimension(32767, 50));
        pioche1 = new boundary.presentation.components.Pioche();
        fillerPioche2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        panelJoueur1 = new javax.swing.JPanel();
        panelInfosJ1 = new javax.swing.JPanel();
        jaugeDePopularitePanel1 = new boundary.presentation.components.JaugeDePopularitePanel();
        jaugeDeViePanel1 = new boundary.presentation.components.JaugeDeViePanel();
        profilJoueurPanel1 = new boundary.presentation.components.ProfilJoueurPanel();
        panelMainJ1 = new javax.swing.JPanel();
        fillerMain1J1 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(60, 32767));
        fillerEspaceCarte1J1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerEspaceCarte2J1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerEspaceCarte3J1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerMain2J1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(100, 32767));
        timerPanel1 = new boundary.presentation.components.TimerPanel();
        panelJoueur2 = new javax.swing.JPanel();
        panelInfosJ2 = new javax.swing.JPanel();
        jaugeDePopularitePanel2 = new boundary.presentation.components.JaugeDePopularitePanel();
        jaugeDeViePanel2 = new boundary.presentation.components.JaugeDeViePanel();
        profilJoueurPanel2 = new boundary.presentation.components.ProfilJoueurPanel();
        panelMainJ2 = new javax.swing.JPanel();
        fillerMain1J2 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(60, 32767));
        fillerEspaceCarte1J2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerEspaceCarte2J2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerEspaceCarte3J2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fillerMain2J2 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(60, 32767));
        descriptionPanel1 = new boundary.presentation.components.DescriptionPanel();
        jPanel2 = new javax.swing.JPanel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setOpaque(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new java.awt.BorderLayout());

        panelCommun.setOpaque(false);
        panelCommun.setLayout(new java.awt.BorderLayout());

        panelZonesPopularite.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        panelZonesPopularite.setOpaque(false);
        panelZonesPopularite.setLayout(new java.awt.GridLayout(2, 0));

        javax.swing.GroupLayout zonePopularitePanel1Layout = new javax.swing.GroupLayout(zonePopularitePanel1);
        zonePopularitePanel1.setLayout(zonePopularitePanel1Layout);
        zonePopularitePanel1Layout.setHorizontalGroup(
            zonePopularitePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        zonePopularitePanel1Layout.setVerticalGroup(
            zonePopularitePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        panelZonesPopularite.add(zonePopularitePanel1);

        javax.swing.GroupLayout zonePopularitePanel2Layout = new javax.swing.GroupLayout(zonePopularitePanel2);
        zonePopularitePanel2.setLayout(zonePopularitePanel2Layout);
        zonePopularitePanel2Layout.setHorizontalGroup(
            zonePopularitePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        zonePopularitePanel2Layout.setVerticalGroup(
            zonePopularitePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        panelZonesPopularite.add(zonePopularitePanel2);

        panelCommun.add(panelZonesPopularite, java.awt.BorderLayout.CENTER);

        panelZoneAction.setOpaque(false);
        panelZoneAction.setPreferredSize(new java.awt.Dimension(100, 26));
        panelZoneAction.setLayout(new java.awt.GridLayout(3, 0));
        panelZoneAction.add(fillerZoneAction1);

        panelZoneAction1.setBackground(new java.awt.Color(204, 255, 102));
        panelZoneAction1.setPreferredSize(new java.awt.Dimension(100, 26));
        panelZoneAction1.setLayout(new javax.swing.BoxLayout(panelZoneAction1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel15.setText("ACTION");
        panelZoneAction1.add(jLabel15);

        panelZoneAction.add(panelZoneAction1);
        panelZoneAction.add(fillerZoneAction2);

        panelCommun.add(panelZoneAction, java.awt.BorderLayout.WEST);

        panelPioche.setOpaque(false);
        panelPioche.setPreferredSize(new java.awt.Dimension(100, 26));
        panelPioche.setLayout(new java.awt.GridLayout(3, 0));
        panelPioche.add(fillerPioche1);
        panelPioche.add(pioche1);
        panelPioche.add(fillerPioche2);

        panelCommun.add(panelPioche, java.awt.BorderLayout.EAST);

        jPanel1.add(panelCommun, java.awt.BorderLayout.CENTER);

        panelJoueur1.setOpaque(false);
        panelJoueur1.setLayout(new java.awt.BorderLayout());

        panelInfosJ1.setOpaque(false);
        panelInfosJ1.setLayout(new java.awt.BorderLayout());

        jaugeDePopularitePanel1.setBackground(null);
        jaugeDePopularitePanel1.setOpaque(false);

        javax.swing.GroupLayout jaugeDePopularitePanel1Layout = new javax.swing.GroupLayout(jaugeDePopularitePanel1);
        jaugeDePopularitePanel1.setLayout(jaugeDePopularitePanel1Layout);
        jaugeDePopularitePanel1Layout.setHorizontalGroup(
            jaugeDePopularitePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        jaugeDePopularitePanel1Layout.setVerticalGroup(
            jaugeDePopularitePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        panelInfosJ1.add(jaugeDePopularitePanel1, java.awt.BorderLayout.EAST);

        jaugeDeViePanel1.setOpaque(false);
        panelInfosJ1.add(jaugeDeViePanel1, java.awt.BorderLayout.NORTH);

        profilJoueurPanel1.setOpaque(false);
        panelInfosJ1.add(profilJoueurPanel1, java.awt.BorderLayout.CENTER);

        panelJoueur1.add(panelInfosJ1, java.awt.BorderLayout.WEST);

        panelMainJ1.setOpaque(false);
        panelMainJ1.setLayout(new javax.swing.BoxLayout(panelMainJ1, javax.swing.BoxLayout.LINE_AXIS));
        panelMainJ1.add(fillerMain1J1);
        panelMainJ1.add(fillerEspaceCarte1J1);
        panelMainJ1.add(fillerEspaceCarte2J1);
        panelMainJ1.add(fillerEspaceCarte3J1);
        panelMainJ1.add(fillerMain2J1);
        panelMainJ1.add(timerPanel1);

        panelJoueur1.add(panelMainJ1, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelJoueur1, java.awt.BorderLayout.SOUTH);

        panelJoueur2.setOpaque(false);
        panelJoueur2.setLayout(new java.awt.BorderLayout());

        panelInfosJ2.setOpaque(false);
        panelInfosJ2.setLayout(new java.awt.BorderLayout());

        jaugeDePopularitePanel2.setOpaque(false);

        javax.swing.GroupLayout jaugeDePopularitePanel2Layout = new javax.swing.GroupLayout(jaugeDePopularitePanel2);
        jaugeDePopularitePanel2.setLayout(jaugeDePopularitePanel2Layout);
        jaugeDePopularitePanel2Layout.setHorizontalGroup(
            jaugeDePopularitePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jaugeDePopularitePanel2Layout.setVerticalGroup(
            jaugeDePopularitePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        panelInfosJ2.add(jaugeDePopularitePanel2, java.awt.BorderLayout.EAST);

        jaugeDeViePanel2.setOpaque(false);
        panelInfosJ2.add(jaugeDeViePanel2, java.awt.BorderLayout.SOUTH);

        profilJoueurPanel2.setOpaque(false);
        panelInfosJ2.add(profilJoueurPanel2, java.awt.BorderLayout.CENTER);

        panelJoueur2.add(panelInfosJ2, java.awt.BorderLayout.WEST);

        panelMainJ2.setOpaque(false);
        panelMainJ2.setLayout(new javax.swing.BoxLayout(panelMainJ2, javax.swing.BoxLayout.LINE_AXIS));
        panelMainJ2.add(fillerMain1J2);
        panelMainJ2.add(fillerEspaceCarte1J2);
        panelMainJ2.add(fillerEspaceCarte2J2);
        panelMainJ2.add(fillerEspaceCarte3J2);
        panelMainJ2.add(fillerMain2J2);

        descriptionPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                descriptionPanel1MousePressed(evt);
            }
        });
        panelMainJ2.add(descriptionPanel1);

        panelJoueur2.add(panelMainJ2, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelJoueur2, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1);

        backgroundLabel.setMaximumSize(new java.awt.Dimension(1080, 720));
        backgroundLabel.setMinimumSize(new java.awt.Dimension(1080, 720));
        backgroundLabel.setOpaque(true);
        backgroundLabel.setPreferredSize(new java.awt.Dimension(1080, 720));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backgroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backgroundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        System.out.println("boundary.presentation.Plateau.formMousePressed()");
    }//GEN-LAST:event_formMousePressed

    private void descriptionPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionPanel1MousePressed
        // TODO add your handling code here:
        //pour l'instant le code est dans un event mousePressed mais l'idée
        //serait d'appeler la fonction losqu'une carte est jouée
        descriptionPanel1.setDescription("une description");
    }//GEN-LAST:event_descriptionPanel1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private boundary.presentation.components.DescriptionPanel descriptionPanel1;
    private javax.swing.Box.Filler fillerEspaceCarte1J1;
    private javax.swing.Box.Filler fillerEspaceCarte1J2;
    private javax.swing.Box.Filler fillerEspaceCarte2J1;
    private javax.swing.Box.Filler fillerEspaceCarte2J2;
    private javax.swing.Box.Filler fillerEspaceCarte3J1;
    private javax.swing.Box.Filler fillerEspaceCarte3J2;
    private javax.swing.Box.Filler fillerMain1J1;
    private javax.swing.Box.Filler fillerMain1J2;
    private javax.swing.Box.Filler fillerMain2J1;
    private javax.swing.Box.Filler fillerMain2J2;
    private javax.swing.Box.Filler fillerPioche1;
    private javax.swing.Box.Filler fillerPioche2;
    private javax.swing.Box.Filler fillerZoneAction1;
    private javax.swing.Box.Filler fillerZoneAction2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private boundary.presentation.components.JaugeDePopularitePanel jaugeDePopularitePanel1;
    private boundary.presentation.components.JaugeDePopularitePanel jaugeDePopularitePanel2;
    private boundary.presentation.components.JaugeDeViePanel jaugeDeViePanel1;
    private boundary.presentation.components.JaugeDeViePanel jaugeDeViePanel2;
    private javax.swing.JPanel panelCommun;
    private javax.swing.JPanel panelInfosJ1;
    private javax.swing.JPanel panelInfosJ2;
    private javax.swing.JPanel panelJoueur1;
    private javax.swing.JPanel panelJoueur2;
    private javax.swing.JPanel panelMainJ1;
    private javax.swing.JPanel panelMainJ2;
    private javax.swing.JPanel panelPioche;
    private javax.swing.JPanel panelZoneAction;
    private javax.swing.JPanel panelZoneAction1;
    private javax.swing.JPanel panelZonesPopularite;
    private boundary.presentation.components.Pioche pioche1;
    private boundary.presentation.components.ProfilJoueurPanel profilJoueurPanel1;
    private boundary.presentation.components.ProfilJoueurPanel profilJoueurPanel2;
    private boundary.presentation.components.TimerPanel timerPanel1;
    private boundary.presentation.components.ZonePopularitePanel zonePopularitePanel1;
    private boundary.presentation.components.ZonePopularitePanel zonePopularitePanel2;
    // End of variables declaration//GEN-END:variables
}
