/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary.presentation;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import model.Joueur;

/**
 *
 * @author ember
 */
public class Plateau extends javax.swing.JFrame {

    /**
     * Creates new form Plateau
     */
    public Plateau() {
        initComponents();
        setImage();
    }

    public void setImage(){
        BufferedImage image=ChargeurImage.chargerImage("presentation/plateau_background.png");
        Image imageEchelle;
        imageEchelle = image.getScaledInstance(backgroundLabel.getWidth(), backgroundLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon typeIcon=new ImageIcon(imageEchelle);
        backgroundLabel.setIcon(typeIcon);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelJoueur2 = new javax.swing.JPanel();
        panelInfosJ2 = new javax.swing.JPanel();
        panelImageJ2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelPopulariteJ2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelVieJ2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelMainJ2 = new javax.swing.JPanel();
        fillerMain1J2 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(60, 32767));
        panelCarte1J2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fillerEspaceCarte1J2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        panelCarte2J2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fillerEspaceCarte2J2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        panelCarte3J2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fillerEspaceCarte3J2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        panelCarte4J2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fillerMain2J2 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(60, 32767));
        panelDescriptionCarte = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panelCommun = new javax.swing.JPanel();
        panelZonesPopularite = new javax.swing.JPanel();
        panelZonePopulariteJ2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelZonePopulariteJ1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panelZoneAction = new javax.swing.JPanel();
        fillerZoneAction1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 150), new java.awt.Dimension(32767, 50));
        panelZoneAction1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        fillerZoneAction2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        panelPioche = new javax.swing.JPanel();
        fillerPioche1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 150), new java.awt.Dimension(32767, 50));
        panelZoneAction3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        fillerPioche2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        panelJoueur1 = new javax.swing.JPanel();
        panelInfosJ1 = new javax.swing.JPanel();
        panelImageJ1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelPopulariteJ1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        panelVieJ1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        panelMainJ1 = new javax.swing.JPanel();
        fillerMain1J1 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(60, 32767));
        cartePanel1 = new boundary.presentation.CartePanel();
        fillerEspaceCarte1J1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        panelCarte2J1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        fillerEspaceCarte2J1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        panelCarte3J1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        fillerEspaceCarte3J1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        panelCarte4J1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        fillerMain2J1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(100, 32767));
        panelTimerTour = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLayeredPane1.setLayout(new java.awt.BorderLayout());

        panelJoueur2.setOpaque(false);
        panelJoueur2.setLayout(new java.awt.BorderLayout());

        panelInfosJ2.setLayout(new java.awt.BorderLayout());

        panelImageJ2.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setText("IMAGE");
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 70));
        panelImageJ2.add(jLabel1);

        panelInfosJ2.add(panelImageJ2, java.awt.BorderLayout.CENTER);

        panelPopulariteJ2.setBackground(new java.awt.Color(204, 0, 51));

        jLabel2.setText("P");
        panelPopulariteJ2.add(jLabel2);

        panelInfosJ2.add(panelPopulariteJ2, java.awt.BorderLayout.WEST);

        panelVieJ2.setBackground(new java.awt.Color(102, 255, 0));

        jLabel3.setText("VIE");
        panelVieJ2.add(jLabel3);

        panelInfosJ2.add(panelVieJ2, java.awt.BorderLayout.SOUTH);

        panelJoueur2.add(panelInfosJ2, java.awt.BorderLayout.WEST);

        panelMainJ2.setOpaque(false);
        panelMainJ2.setLayout(new javax.swing.BoxLayout(panelMainJ2, javax.swing.BoxLayout.LINE_AXIS));
        panelMainJ2.add(fillerMain1J2);

        panelCarte1J2.setBackground(new java.awt.Color(204, 102, 255));
        panelCarte1J2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        jLabel6.setText("CARTE 1");
        panelCarte1J2.add(jLabel6);

        panelMainJ2.add(panelCarte1J2);
        panelMainJ2.add(fillerEspaceCarte1J2);

        panelCarte2J2.setBackground(new java.awt.Color(204, 102, 255));
        panelCarte2J2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        jLabel7.setText("CARTE 2");
        panelCarte2J2.add(jLabel7);

        panelMainJ2.add(panelCarte2J2);
        panelMainJ2.add(fillerEspaceCarte2J2);

        panelCarte3J2.setBackground(new java.awt.Color(204, 102, 255));
        panelCarte3J2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        jLabel8.setText("CARTE 3");
        panelCarte3J2.add(jLabel8);

        panelMainJ2.add(panelCarte3J2);
        panelMainJ2.add(fillerEspaceCarte3J2);

        panelCarte4J2.setBackground(new java.awt.Color(204, 102, 255));
        panelCarte4J2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        jLabel9.setText("CARTE 4");
        panelCarte4J2.add(jLabel9);

        panelMainJ2.add(panelCarte4J2);
        panelMainJ2.add(fillerMain2J2);

        panelDescriptionCarte.setBackground(new java.awt.Color(0, 102, 102));

        jLabel14.setText("DESC");
        panelDescriptionCarte.add(jLabel14);

        panelMainJ2.add(panelDescriptionCarte);

        panelJoueur2.add(panelMainJ2, java.awt.BorderLayout.CENTER);

        jLayeredPane1.add(panelJoueur2, java.awt.BorderLayout.NORTH);

        panelCommun.setOpaque(false);
        panelCommun.setLayout(new java.awt.BorderLayout());

        panelZonesPopularite.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        panelZonesPopularite.setOpaque(false);
        panelZonesPopularite.setLayout(new java.awt.GridLayout(2, 0));

        panelZonePopulariteJ2.setBackground(new java.awt.Color(255, 204, 153));

        jLabel11.setText("ZONE POPULARITE J2");
        panelZonePopulariteJ2.add(jLabel11);

        panelZonesPopularite.add(panelZonePopulariteJ2);

        panelZonePopulariteJ1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel12.setText("ZONE POPULARITE J1");
        panelZonePopulariteJ1.add(jLabel12);

        panelZonesPopularite.add(panelZonePopulariteJ1);

        panelCommun.add(panelZonesPopularite, java.awt.BorderLayout.CENTER);

        panelZoneAction.setPreferredSize(new java.awt.Dimension(100, 26));
        panelZoneAction.setLayout(new java.awt.GridLayout(3, 0));
        panelZoneAction.add(fillerZoneAction1);

        panelZoneAction1.setBackground(new java.awt.Color(204, 255, 102));
        panelZoneAction1.setPreferredSize(new java.awt.Dimension(100, 26));
        panelZoneAction1.setLayout(new javax.swing.BoxLayout(panelZoneAction1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel15.setText("ACTION");
        panelZoneAction1.add(jLabel15);

        panelZoneAction.add(panelZoneAction1);
        panelZoneAction.add(fillerZoneAction2);

        panelCommun.add(panelZoneAction, java.awt.BorderLayout.WEST);

        panelPioche.setPreferredSize(new java.awt.Dimension(100, 26));
        panelPioche.setLayout(new java.awt.GridLayout(3, 0));
        panelPioche.add(fillerPioche1);

        panelZoneAction3.setBackground(new java.awt.Color(204, 255, 102));
        panelZoneAction3.setPreferredSize(new java.awt.Dimension(100, 26));
        panelZoneAction3.setLayout(new javax.swing.BoxLayout(panelZoneAction3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel16.setText("PIOCHE");
        panelZoneAction3.add(jLabel16);

        panelPioche.add(panelZoneAction3);
        panelPioche.add(fillerPioche2);

        panelCommun.add(panelPioche, java.awt.BorderLayout.EAST);

        jLayeredPane1.add(panelCommun, java.awt.BorderLayout.CENTER);

        panelJoueur1.setOpaque(false);
        panelJoueur1.setLayout(new java.awt.BorderLayout());

        panelInfosJ1.setLayout(new java.awt.BorderLayout());

        panelImageJ1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel4.setText("IMAGE");
        jLabel4.setPreferredSize(new java.awt.Dimension(70, 70));
        panelImageJ1.add(jLabel4);

        panelInfosJ1.add(panelImageJ1, java.awt.BorderLayout.CENTER);

        panelPopulariteJ1.setBackground(new java.awt.Color(204, 0, 51));

        jLabel17.setText("P");
        panelPopulariteJ1.add(jLabel17);

        panelInfosJ1.add(panelPopulariteJ1, java.awt.BorderLayout.WEST);

        panelVieJ1.setBackground(new java.awt.Color(102, 255, 0));

        jLabel18.setText("VIE");
        panelVieJ1.add(jLabel18);

        panelInfosJ1.add(panelVieJ1, java.awt.BorderLayout.NORTH);

        panelJoueur1.add(panelInfosJ1, java.awt.BorderLayout.WEST);

        panelMainJ1.setOpaque(false);
        panelMainJ1.setLayout(new javax.swing.BoxLayout(panelMainJ1, javax.swing.BoxLayout.LINE_AXIS));
        panelMainJ1.add(fillerMain1J1);

        cartePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cartePanel1MousePressed(evt);
            }
        });
        panelMainJ1.add(cartePanel1);
        panelMainJ1.add(fillerEspaceCarte1J1);

        panelCarte2J1.setBackground(new java.awt.Color(153, 102, 255));
        panelCarte2J1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        jLabel20.setText("CARTE 2");
        panelCarte2J1.add(jLabel20);

        panelMainJ1.add(panelCarte2J1);
        panelMainJ1.add(fillerEspaceCarte2J1);

        panelCarte3J1.setBackground(new java.awt.Color(153, 102, 255));
        panelCarte3J1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        jLabel21.setText("CARTE 3");
        panelCarte3J1.add(jLabel21);

        panelMainJ1.add(panelCarte3J1);
        panelMainJ1.add(fillerEspaceCarte3J1);

        panelCarte4J1.setBackground(new java.awt.Color(153, 102, 255));
        panelCarte4J1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        jLabel22.setText("CARTE 4");
        panelCarte4J1.add(jLabel22);

        panelMainJ1.add(panelCarte4J1);
        panelMainJ1.add(fillerMain2J1);

        panelTimerTour.setBackground(new java.awt.Color(102, 102, 255));

        jLabel13.setText("TIMER");
        panelTimerTour.add(jLabel13);

        panelMainJ1.add(panelTimerTour);

        panelJoueur1.add(panelMainJ1, java.awt.BorderLayout.CENTER);

        jLayeredPane1.add(panelJoueur1, java.awt.BorderLayout.SOUTH);

        backgroundLabel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        backgroundLabel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        backgroundLabel.setOpaque(true);
        backgroundLabel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(backgroundLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(backgroundLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cartePanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartePanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartePanel1MousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        System.out.println("boundary.presentation.Plateau.formMousePressed()");
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private boundary.presentation.CartePanel cartePanel1;
    private javax.swing.Box.Filler fillerEspaceCarte1J1;
    private javax.swing.Box.Filler fillerEspaceCarte1J2;
    private javax.swing.Box.Filler fillerEspaceCarte2J1;
    private javax.swing.Box.Filler fillerEspaceCarte2J2;
    private javax.swing.Box.Filler fillerEspaceCarte3J1;
    private javax.swing.Box.Filler fillerEspaceCarte3J2;
    private javax.swing.Box.Filler fillerMain1J1;
    private javax.swing.Box.Filler fillerMain1J2;
    private javax.swing.Box.Filler fillerMain2J1;
    private javax.swing.Box.Filler fillerMain2J2;
    private javax.swing.Box.Filler fillerPioche1;
    private javax.swing.Box.Filler fillerPioche2;
    private javax.swing.Box.Filler fillerZoneAction1;
    private javax.swing.Box.Filler fillerZoneAction2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel panelCarte1J2;
    private javax.swing.JPanel panelCarte2J1;
    private javax.swing.JPanel panelCarte2J2;
    private javax.swing.JPanel panelCarte3J1;
    private javax.swing.JPanel panelCarte3J2;
    private javax.swing.JPanel panelCarte4J1;
    private javax.swing.JPanel panelCarte4J2;
    private javax.swing.JPanel panelCommun;
    private javax.swing.JPanel panelDescriptionCarte;
    private javax.swing.JPanel panelImageJ1;
    private javax.swing.JPanel panelImageJ2;
    private javax.swing.JPanel panelInfosJ1;
    private javax.swing.JPanel panelInfosJ2;
    private javax.swing.JPanel panelJoueur1;
    private javax.swing.JPanel panelJoueur2;
    private javax.swing.JPanel panelMainJ1;
    private javax.swing.JPanel panelMainJ2;
    private javax.swing.JPanel panelPioche;
    private javax.swing.JPanel panelPopulariteJ1;
    private javax.swing.JPanel panelPopulariteJ2;
    private javax.swing.JPanel panelTimerTour;
    private javax.swing.JPanel panelVieJ1;
    private javax.swing.JPanel panelVieJ2;
    private javax.swing.JPanel panelZoneAction;
    private javax.swing.JPanel panelZoneAction1;
    private javax.swing.JPanel panelZoneAction3;
    private javax.swing.JPanel panelZonePopulariteJ1;
    private javax.swing.JPanel panelZonePopulariteJ2;
    private javax.swing.JPanel panelZonesPopularite;
    // End of variables declaration//GEN-END:variables
}
