/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.presentation;

/**
 *
 * @author David Marquet
 */
public class TimerPanel extends javax.swing.JPanel {

    /**
     * Creates new form TimerPanel
     */
    javax.swing.Timer timer;
    private int decompte;
    private static final int TEMPS = 60;
    
    public TimerPanel() {
        initComponents();
        this.timer = new javax.swing.Timer(1000, (e) -> { timerEventHandler(e); });
        timer.start();
        this.decompte = TEMPS;
    }
    
    private void timerEventHandler(java.awt.event.ActionEvent e) {
        this.decompte --;
        if (this.decompte < 0){
            timerTxt.setText(String.valueOf("Temps écoulé"));
            timer.stop();
            // TODO  : action associé quand le temps est écoulé
        }else{
           timerTxt.setText(String.valueOf(this.decompte)); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomTimer = new javax.swing.JLabel();
        timerTxt = new javax.swing.JLabel();

        nomTimer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomTimer.setText("TEMPS DU TOUR");

        timerTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timerTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerTxt.setText(String.valueOf(TEMPS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(nomTimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerTxt)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomTimer;
    private javax.swing.JLabel timerTxt;
    // End of variables declaration//GEN-END:variables
}
